### ISSUE TITLE
Add init/finalize functions that are called when a driver is mounted/unmounted

### ISSUE THREAD

**Issue by flongo82** [MDSLab/s4t-lightning-rod#13]
The driver developer has to be able to provide an init/finalize function (within the .js module implementing the functions of the driver) that will be called when the driver is mounted/unmounted. 

For example, it could be used by the developer to enable/disable IIO devices if the driver needs them.

**Comment by npeditto** [comment]
This functionality is now available: a driver developer must specify an Init() and a Finalize() function that will be called by the driver manager of lightning-rod in order to execute the initialization procedures (before the mounting of the driver) and the finalization procedures (before the unmounting of the driver).
